# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\terraform\dev'
    backendServiceArm: 'Ironstone-CSP-ScanReach-IT(7399e158-d7a6-4421-872d-79df9badefca)'
    backendAzureRmResourceGroupName: 'terraform-state'
    backendAzureRmStorageAccountName: 'srttfstate'
    backendAzureRmContainerName: 'state'
    backendAzureRmKey: 'RS-dev-tf_dorp.tfstate'

